# 帖子列表
GET https://bbs.mobileapi.hupu.com/3/8.0.32/topics/getTopicThreads
?bddid=7KR23BILT3NEAJZSXKABEN3A3WPCZ2HTAVWDBHDWVM6E3GVQAAOQ01
&client=34C1DCA0-3B56-555C-B2EF-D94614CB31C9
&clientId=135015318
&crt=1672813210
&deviceId=Bk58mCtybJ1Jhp5a1S/I36yGlSNi2aYGZ43LULUHfvYjRG9MyiCxonMropgbR8U980BLn5FmCFledXiyt/zUSvA%3D%3D
&newapp=1
&night=0
&page=1
&sign=962f4ab7cdcf409f2cc99a6d925f07f6
&stamp=0
# 全部： 2
# 24小时榜： 4 
# 精华： 3
&tab_type=2
&time_zone=Asia/Shanghai
# 专区编号， 
# 步行街是1， 
# 足球话题区是184
&topic_id=1

###跟帖请求
GET https://bbs.mobileapi.hupu.com/3/8.0.32/threads/getCheckReply
?bddid=7KR23BILT3NEAJZSXKABEN3A3WPCZ2HTAVWDBHDWVM6E3GVQAAOQ01
&client=34C1DCA0-3B56-555C-B2EF-D94614CB31C9
&clientId=135015318
&crt=1672884741
&deviceId=BU1ZfVbXdfZpvWIfzRWGG6WrwdvfXHN70dB2gFAZq8JER5z0DAMELUkzQ3nvLHTBXfFBn8mXIIFlw69OtETnTLw%3D%3D
&fid=1389
&maxpid=
&newapp=1
&night=0
&offline=json
&order=light
&page_type=3
&pid=286208
&sign=a19ac8423588f70093f0814f05a14f05
&tid=57252723
&time_zone=Asia/Shanghai
&topicId=184
### 步行街
GET https://bbs.mobileapi.hupu.com/3/8.0.32/topics/getTopicThreads
?bddid=7KR23BILT3NEAJZSXKABEN3A3WPCZ2HTAVWDBHDWVM6E3GVQAAOQ01
&client=34C1DCA0-3B56-555C-B2EF-D94614CB31C9
&clientId=135015318
&crt=1672885408
&deviceId=BU1ZfVbXdfZpvWIfzRWGG6WrwdvfXHN70dB2gFAZq8JER5z0DAMELUkzQ3nvLHTBXfFBn8mXIIFlw69OtETnTLw%3D%3D
&newapp=1
&night=0
&page=1
&sign=6b3a66dadf4dc1d1f550efea8c90d024
&stamp=0
&tab_type=3
&time_zone=Asia/Shanghai
&topic_id=1

### 帖子详情页
GET https://bbs.mobileapi.hupu.com/3/8.0.32/threads/57276447
?bddid=7KR23BILT3NEAJZSXKABEN3A3WPCZ2HTAVWDBHDWVM6E3GVQAAOQ01
&client=34C1DCA0-3B56-555C-B2EF-D94614CB31C9
&clientId=135015318
&crt=1672969937
&deviceId=Bp/nbo4kxe9YGRU9jlyJpwFXNUPadcULJIKfONF8GLv1Evcj6Juzsn47heeBnXFgIWUvSjLP1G2YemyD5ei8xjg%3D%3D
&newapp=1
&night=0
&sign=4b6acbe7170f693977f1c9e62167b6e2
&time_zone=Asia/Shanghai

###
GET http://localhost:8080/test
content-type: application/json

https://bbs.mobileapi.hupu.com/3/8.0.32/threads/57276447?bddid=7KR23BILT3NEAJZSXKABEN3A3WPCZ2HTAVWDBHDWVM6E3GVQAAOQ01&client=34C1DCA0-3B56-555C-B2EF-D94614CB31C9&clientId=135015318&crt=1672969937&deviceId=Bp%2Fnbo4kxe9YGRU9jlyJpwFXNUPadcULJIKfONF8GLv1Evcj6Juzsn47heeBnXFgIWUvSjLP1G2YemyD5ei8xjg%3D%3D&newapp=1&night=0&sign=4b6acbe7170f693977f1c9e62167b6e2&time_zone=Asia%2FShanghai